server:
  port: 808

spring:
  messages:
    basename: i18n/Messages,i18n/Pages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                           # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver                            # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/onlinetutor?serverTimezone=GMT%2B8   # 数据库连接地址
    username: root                                                         # 数据库用户名
    password: 1234                                                          # 数据库连接密码
    dbcp2:                                                                 # 进行数据库连接池的配置
      min-idle: 5                                                          # 数据库连接池的最小维持连接数
      initial-size: 5                                                      # 初始化提供的连接数
      max-total: 5                                                         # 最大的连接数
      max-wait-millis: 200                                                 # 等待连接获取的最大超时时间
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
## 该配置节点为独立的节点，这个配置放在spring的节点下将导致配置无法被识别
mybatis:
  mapper-locations: classpath:mappers/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.aylfq5.online.tutor.domain  # 注意：对应实体类的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 七牛配置信息

qiniu:
  accesskey: WbwkAoZSrnpf6Xf78TjfntuuKms0Uo2LnW5SVa-r
  secretkey: 73xQTIe5pXUQeeUnU_kbYkPv9gC2iAuwFYQeVh7H
  bucket: aylfq5_online_tutor
  source-prefix: http://porbzia1c.bkt.clouddn.com/